name 'aapp'
maintainer 'UAF GINA'
maintainer_email 'support+chef@gina.alaska.edu'
license 'APACHE2'
description 'Installs/Configures aapp'
long_description 'Installs/Configures aapp'
version '0.1.0'

depends 'yum-gina'
depends 'line'